// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmKDyOpxr4GVJrkQGShcFIPxyWTZfvbz0',
    appId: '1:956171467987:web:f0ef89020c69cc0caee826',
    messagingSenderId: '956171467987',
    projectId: 'harita-odev-5c64b',
    authDomain: 'harita-odev-5c64b.firebaseapp.com',
    storageBucket: 'harita-odev-5c64b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH98OTn2ibQz6_y93ZOCea7OJ4_r2Lk90',
    appId: '1:956171467987:android:1058a1749f68acf6aee826',
    messagingSenderId: '956171467987',
    projectId: 'harita-odev-5c64b',
    storageBucket: 'harita-odev-5c64b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-Vaas_KSik8lTlMkF4oGMUE1HFJz2bHM',
    appId: '1:956171467987:ios:8f06def56df97563aee826',
    messagingSenderId: '956171467987',
    projectId: 'harita-odev-5c64b',
    storageBucket: 'harita-odev-5c64b.appspot.com',
    iosBundleId: 'com.example.googleMapsOdev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-Vaas_KSik8lTlMkF4oGMUE1HFJz2bHM',
    appId: '1:956171467987:ios:53f54322223bda90aee826',
    messagingSenderId: '956171467987',
    projectId: 'harita-odev-5c64b',
    storageBucket: 'harita-odev-5c64b.appspot.com',
    iosBundleId: 'com.example.googleMapsOdev.RunnerTests',
  );
}
